In [1]:
from Environnement import *
from Player import *
from utils import *
import numpy as np

In [2]:
env = Environnement(n_tasks = 2,n_players = 2)

In [3]:
env.getUtilityShape()
env.utility[1][1][0] = 15
env.utility[1][1][1] = 15
env.utility

array([[[ 5,  6],
        [ 8,  1]],

       [[ 5,  2],
        [15, 15]]])

In [16]:
env.allocation[1] = 1
env.allocation[1] = 1

In [17]:
vehicle = 1
new_all = list(env.allocation)
new_all[vehicle] = slice(None)
new_all

[0, slice(None, None, None)]

In [18]:
env.getBestActionPerPlayer()

Running on :  A
Running on :  B


(array([8, 6]), array([0, 1]))

In [19]:
env.is_EN_v()

True

In [20]:
env.is_EN()

(True, -1)

In [21]:
P = RandomPlayer(env, 0)
P

In [22]:
import threading
import time
class myThread (threading.Thread):

   def __init__(self, threadID, name, counter):
      threading.Thread.__init__(self)
      self.threadID = threadID
      self.name = name
      self.counter = counter


   def run(self):
      print ("Starting " + self.name)
      for i in range(0,100):
          print("Running on : ", self.name)
          time.sleep(1)
      print ("Exiting " + self.name)

In [23]:
env = Environnement(n_tasks = 2,n_players = 2)
P1 = RandomPlayer(env, 0)
P2 = RandomPlayer(env, 1)
for i in range(10):
    env.play(P1.id, P1.select_action())
    env.play(P2.id, P2.select_action())
    print(env.allocation)

Running on :  A
Running on :  B
[1 0]
[0 1]
[0 0]
[1 1]
[1 1]
[1 1]
[1 0]
[1 1]
[1 0]
[0 0]


In [24]:
t1 = myThread(1,"A",0)
t2 = myThread(1,"B",0)
t1.start()
t2.start()

Starting A
Running on :  A
Starting B
Running on :  B
Running on :  A
Running on :  B


In [27]:
env = Environnement(n_tasks = 2,n_players = 2)
P1 = RandomPlayer(env, 0)
P2 = BRPlayer(env, 1)
P1.select_action()

0

In [28]:
for i in range(10):
    env.play(P1.id, P1.select_action())
    env.play(P2.id, P2.select_action())
    print(env.allocation)

Running on :  A
Running on :  B
[1 0]
[1 0]
[1 0]
[1 0]
[0 0]
[0 0]
[0 0]
[1 0]
[0 0]
[1 0]
Running on :  B
Running on :  A
Running on :  A
Running on :  B
Running on : Running on :  A
 B
Running on :  A
Running on :  B
Running on :  A
Running on :  B
Running on :  A
Running on :  B
Running on : Running on :  A
 B
Running on :  A
Running on :  B
Running on :  A
Running on :  B
Running on :  A
Running on :  B
Running on :  A
Running on :  B
Running on :  A
Running on :  B
Running on :  A
Running on :  B
Running on :  A
Running on :  B
Running on :  A
Running on :  B
Running on :  A
Running on :  B
Running on :  A
Running on :  B
Running on :  A
Running on :  B
Running on :  A
Running on :  B
Running on :  A
Running on :  B
Running on :  A
Running on :  B
Running on :  A
Running on :  B
Running on :  A
Running on :  B
Running on :  A
Running on :  B
Running on :  A
Running on :  B
Running on :  Running on :  B
A
Running on :  A
Running on :  B
Running on : Running on :  B A

Running on :

In [52]:
env = Environnement(n_tasks = 3,n_players = 3)
env.utility[:][0][:][1]

array([[9, 2, 4],
       [3, 1, 4],
       [1, 5, 3]])

In [47]:
env.utility[:][0][1]*[0.2, 0.8]

array([1.8, 4.8])

In [36]:
env.utility[0][:][:][0]

array([[7, 1, 4],
       [3, 1, 6],
       [7, 6, 3],
       [5, 0, 8]])