In [1]:
from Environnement import *
from Player import *
from utils import *
import numpy as np

In [2]:
env = Environnement(n_tasks = 2,n_players = 2)

In [3]:
env.getUtilityShape()
env.utility[1][1][0] = 15
env.utility[1][1][1] = 15
env.utility

array([[[ 7,  8],
        [ 6,  8]],

       [[ 0,  5],
        [15, 15]]])

In [4]:
env.allocation[1] = 1
env.allocation[1] = 1

In [5]:
vehicle = 1
new_all = list(env.allocation)
new_all[vehicle] = slice(None)
new_all

[0, slice(None, None, None)]

In [6]:
env.getBestActionPerPlayer()

(array([15,  8]), array([1, 0]))

In [7]:
env.is_EN_v()

True

In [8]:
env.is_EN()

(False, 0)

In [9]:
P = RandomPlayer(env, 0)
P

In [10]:
import threading
import time
class myThread (threading.Thread):

   def __init__(self, threadID, name, counter):
      threading.Thread.__init__(self)
      self.threadID = threadID
      self.name = name
      self.counter = counter


   def run(self):
      print ("Starting " + self.name)
      for i in range(0,100):
          print("Running on : ", self.name)
          time.sleep(1)
      print ("Exiting " + self.name)

In [11]:
env = Environnement(n_tasks = 2,n_players = 2)
P1 = RandomPlayer(env, 0)
P2 = RandomPlayer(env, 1)
for i in range(10):
    env.play(P1.id, P1.select_action())
    env.play(P2.id, P2.select_action())
    print(env.allocation)

[1 1]
[0 0]
[0 1]
[0 0]
[0 1]
[1 0]
[0 1]
[0 0]
[0 1]
[0 0]


In [12]:
t1 = myThread(1,"A",0)
t2 = myThread(1,"B",0)
t1.start()
t2.start()

Starting AStarting B
Running on :  B

Running on :  A


In [13]:
env = Environnement(n_tasks = 2,n_players = 2)
P1 = RandomPlayer(env, 0)
P2 = BRPlayer(env, 1)
P1.select_action()

0

In [14]:
for i in range(10):
    env.play(P1.id, P1.select_action())
    env.play(P2.id, P2.select_action())
    print(env.allocation)

[1 0]
[0 1]
[0 1]
[0 1]
[0 1]
[0 1]
[1 0]
[1 0]
[0 1]
[0 1]
Running on :  B
Running on :  A


In [15]:
env = Environnement(n_tasks = 3,n_players = 3)
env.utility[:][0][:][1]

array([[1, 3, 6],
       [8, 4, 7],
       [7, 8, 2]])

In [26]:
P1 = RandomPlayer(env, 0)
P2 = RandomPlayer(env, 1)
P3 = RandomPlayer(env, 2)
t = threading.Thread(name="Player "+str(P1.id), target=P1.getWorkerFunction(100,verbose=True))
w = threading.Thread(name="Player "+str(P2.id), target=P2.getWorkerFunction(100,verbose=True))
s = threading.Thread(name="Player "+str(P3.id), target=P3.getWorkerFunction(100,verbose=True))
w.start()
t.start()
s.start()
w.join()
t.join()
s.join()

tion [2 0 1]
[DEBUG] (Player 0  ) Playing 2
[DEBUG] (Player 0  ) Current allocation [2 0 1]
[DEBUG] (Player 2  ) Playing 1
[DEBUG] (Player 2  ) Current allocation [2 0 1]
[DEBUG] (Player 1  ) Playing 2
[DEBUG] (Player 1  ) Current allocation [2 2 1]
[DEBUG] (Player 0  ) Playing 0
[DEBUG] (Player 0  ) Current allocation [0 2 1]
[DEBUG] (Player 2  ) Playing 0
[DEBUG] (Player 2  ) Current allocation [0 2 0]
[DEBUG] (Player 1  ) Playing 0
[DEBUG] (Player 1  ) Current allocation [0 0 0]
[DEBUG] (Player 0  ) Playing 0
[DEBUG] (Player 0  ) Current allocation [0 0 0]
[DEBUG] (Player 2  ) Playing 2
[DEBUG] (Player 2  ) Current allocation [0 0 2]
[DEBUG] (Player 1  ) Playing 0
[DEBUG] (Player 1  ) Current allocation [0 0 2]
[DEBUG] (Player 0  ) Playing 0
[DEBUG] (Player 0  ) Current allocation [0 0 2]
[DEBUG] (Player 2  ) Playing 0
[DEBUG] (Player 2  ) Current allocation [0 0 0]
[DEBUG] (Player 1  ) Playing 1
[DEBUG] (Player 1  ) Current allocation [0 1 0]
[DEBUG] (Player 0  ) Playing 0
[DEBUG] 

In [27]:
L = []
for agent in env.players:
    arr = env.hist[agent]
    tasks = env.tasks
    freq = np.zeros(env.players.shape)
    for t in tasks:
        k = len(np.where(arr == t)[0])
        freq[t] = k
    L.append(freq / freq.sum())
L = np.array(L)
print(L)

[[0.57425743 0.21782178 0.20792079]
 [0.56105611 0.21122112 0.22772277]
 [0.5379538  0.22112211 0.24092409]]


In [17]:
env.utility[0][:][:][0]

array([[5, 0, 1],
       [8, 1, 5],
       [0, 5, 9]])

In [29]:
t = len(env.players)*[slice(None, None, None)]+[0]
it = np.nditer(env.utility[:,:,:,0], flags=['multi_index'])
for x in it:
    print(it.multi_index, end=" ")

(0, 0, 0) (0, 0, 1) (0, 0, 2) (0, 1, 0) (0, 1, 1) (0, 1, 2) (0, 2, 0) (0, 2, 1) (0, 2, 2) (1, 0, 0) (1, 0, 1) (1, 0, 2) (1, 1, 0) (1, 1, 1) (1, 1, 2) (1, 2, 0) (1, 2, 1) (1, 2, 2) (2, 0, 0) (2, 0, 1) (2, 0, 2) (2, 1, 0) (2, 1, 1) (2, 1, 2) (2, 2, 0) (2, 2, 1) (2, 2, 2) 